user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;

include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # 🔥 Logging Settings (UPDATED)
        ##

        # 👉 JSON format cho Wazuh
        log_format wazuh_json escape=json '{'
          '"time":"$time_iso8601",'
          '"remote_addr":"$remote_addr",'
          '"x_forwarded_for":"$http_x_forwarded_for",'
          '"request":"$request",'
          '"status":$status,'
          '"body_bytes_sent":$body_bytes_sent,'
          '"request_time":$request_time,'
          '"upstream_response_time":"$upstream_response_time",'
          '"upstream_addr":"$upstream_addr",'
          '"user_agent":"$http_user_agent",'
          '"referer":"$http_referer",'
          '"method":"$request_method",'
          '"uri":"$request_uri",'
          '"host":"$host",'
          '"auth_user":"$remote_user"'
        '}';

        # 👉 Áp dụng JSON log
        access_log /var/log/nginx/access.log wazuh_json;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        ##
        # Gzip Settings
        ##

        gzip on;

        map $upstream_http_x_forbidden_redirect $forbidden_url {
            default "";
            "~^https?://" $upstream_http_x_forbidden_redirect;
        }

        ##
        # Virtual Host Configs
        ##
        #limit_req_zone $binary_remote_addr zone=req_limit:10m rate=3r/s;

        limit_req_zone $binary_remote_addr zone=login_limit:10m rate=2r/s;
        limit_conn_zone $binary_remote_addr zone=conn_limit:10m;
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;


}
